// @ts-nocheck
function stryNS_9fa48() {
  var g = typeof globalThis === 'object' && globalThis && globalThis.Math === Math && globalThis || new Function("return this")();
  var ns = g.__stryker__ || (g.__stryker__ = {});
  if (ns.activeMutant === undefined && g.process && g.process.env && g.process.env.__STRYKER_ACTIVE_MUTANT__) {
    ns.activeMutant = g.process.env.__STRYKER_ACTIVE_MUTANT__;
  }
  function retrieveNS() {
    return ns;
  }
  stryNS_9fa48 = retrieveNS;
  return retrieveNS();
}
stryNS_9fa48();
function stryCov_9fa48() {
  var ns = stryNS_9fa48();
  var cov = ns.mutantCoverage || (ns.mutantCoverage = {
    static: {},
    perTest: {}
  });
  function cover() {
    var c = cov.static;
    if (ns.currentTestId) {
      c = cov.perTest[ns.currentTestId] = cov.perTest[ns.currentTestId] || {};
    }
    var a = arguments;
    for (var i = 0; i < a.length; i++) {
      c[a[i]] = (c[a[i]] || 0) + 1;
    }
  }
  stryCov_9fa48 = cover;
  cover.apply(null, arguments);
}
function stryMutAct_9fa48(id) {
  var ns = stryNS_9fa48();
  function isActive(id) {
    if (ns.activeMutant === id) {
      if (ns.hitCount !== void 0 && ++ns.hitCount > ns.hitLimit) {
        throw new Error('Stryker: Hit count limit reached (' + ns.hitCount + ')');
      }
      return true;
    }
    return false;
  }
  stryMutAct_9fa48 = isActive;
  return isActive(id);
}
export const CREATE_LESSON_CARD_SUCCESS = stryMutAct_9fa48("0") ? "" : (stryCov_9fa48("0"), 'CREATE_LESSON_CARD_SUCCESS');
export const CREATE_LESSON_CARD_START = stryMutAct_9fa48("1") ? "" : (stryCov_9fa48("1"), 'CREATE_LESSON_CARD_START');
export const HANDLE_LESSON_CARD_START = stryMutAct_9fa48("2") ? "" : (stryCov_9fa48("2"), 'HANDLE_LESSON_CARD_START');
export const TOOGLE_TEACHER_START = stryMutAct_9fa48("3") ? "" : (stryCov_9fa48("3"), 'TOOGLE_TEACHER_START');
export const GET_LESSONS_CARDS_START = stryMutAct_9fa48("4") ? "" : (stryCov_9fa48("4"), 'GET_LESSONS_CARDS_START');
export const SET_LESSONS_CARDS_START = stryMutAct_9fa48("5") ? "" : (stryCov_9fa48("5"), 'SET_LESSONS_CARDS_START');
export const GET_LESSON_TYPES_START = stryMutAct_9fa48("6") ? "" : (stryCov_9fa48("6"), 'GET_LESSON_TYPES_START');
export const SET_LESSON_TYPES_SUCCESS = stryMutAct_9fa48("7") ? "" : (stryCov_9fa48("7"), 'SET_LESSON_TYPES_SUCCESS');
export const COPY_LESSON_START = stryMutAct_9fa48("8") ? "" : (stryCov_9fa48("8"), 'COPY_LESSON_START');
export const DELETE_LESSON_CARD_START = stryMutAct_9fa48("9") ? "" : (stryCov_9fa48("9"), 'DELETE_LESSON_CARD_START');
export const DELETE_LESSON_CARD_SUCCESS = stryMutAct_9fa48("10") ? "" : (stryCov_9fa48("10"), 'DELETE_LESSON_CARD_SUCCESS');
export const SELECT_LESSON_CARD_SUCCESS = stryMutAct_9fa48("11") ? "" : (stryCov_9fa48("11"), 'SELECT_LESSON_CARD_SUCCESS');
export const UPDATE_LESSON_CARD_SUCCESS = stryMutAct_9fa48("12") ? "" : (stryCov_9fa48("12"), 'UPDATE_LESSON_CARD_SUCCESS');
export const UPDATE_LESSON_CARD_START = stryMutAct_9fa48("13") ? "" : (stryCov_9fa48("13"), 'UPDATE_LESSON_CARD_START');
export const SELECT_GROUP_ID = stryMutAct_9fa48("14") ? "" : (stryCov_9fa48("14"), 'SELECT_GROUP_ID');
export const SET_UNIQUE_ERROR = stryMutAct_9fa48("15") ? "" : (stryCov_9fa48("15"), 'SET_UNIQUE_ERROR');
export const SET_TEMPORARY_SCHEDULES = stryMutAct_9fa48("16") ? "" : (stryCov_9fa48("16"), 'SET_TEMPORARY_SCHEDULES');
export const SET_SCHEDULES_AND_TEMPORARY_SCHEDULES = stryMutAct_9fa48("17") ? "" : (stryCov_9fa48("17"), 'SET_SCHEDULES_AND_TEMPORARY_SCHEDULES');
export const SELECT_TEMPORARY_SCHEDULE = stryMutAct_9fa48("18") ? "" : (stryCov_9fa48("18"), 'SELECT_TEMPORARY_SCHEDULE');
export const SELECT_VACATION = stryMutAct_9fa48("19") ? "" : (stryCov_9fa48("19"), 'SELECT_VACATION');
export const SELECT_TEACHER_ID = stryMutAct_9fa48("20") ? "" : (stryCov_9fa48("20"), 'SELECT_TEACHER_ID');
export const SET_OPEN_SNACKBAR = stryMutAct_9fa48("21") ? "" : (stryCov_9fa48("21"), 'SET_OPEN_SNACKBAR');
export const SET_USERS = stryMutAct_9fa48("22") ? "" : (stryCov_9fa48("22"), 'SET_USERS');
export const SET_USER = stryMutAct_9fa48("23") ? "" : (stryCov_9fa48("23"), 'SET_USER');
export const AUTH_USER = stryMutAct_9fa48("24") ? "" : (stryCov_9fa48("24"), 'AUTH_USER');
export const AUTH_USER_SUCCESS = stryMutAct_9fa48("25") ? "" : (stryCov_9fa48("25"), 'AUTH_USER_SUCCESS');
export const AUTH_USER_ERROR = stryMutAct_9fa48("26") ? "" : (stryCov_9fa48("26"), 'AUTH_USER_ERROR');
export const AUTH_USER_INITIATE_LOGOUT = stryMutAct_9fa48("27") ? "" : (stryCov_9fa48("27"), 'AUTH_USER_INITIATE_LOGOUT');
export const AUTH_USER_LOGOUT = stryMutAct_9fa48("28") ? "" : (stryCov_9fa48("28"), 'AUTH_USER_LOGOUT');
export const AUTH_USER_AUTO_LOGOUT = stryMutAct_9fa48("29") ? "" : (stryCov_9fa48("29"), 'AUTH_USER_AUTO_LOGOUT');
export const AUTH_USER_CHECK_STATE = stryMutAct_9fa48("30") ? "" : (stryCov_9fa48("30"), 'AUTH_USER_CHECK_STATE');
export const SET_AUTH_ERROR = stryMutAct_9fa48("31") ? "" : (stryCov_9fa48("31"), 'SET_AUTH_ERROR');
export const REGISTER_USER = stryMutAct_9fa48("32") ? "" : (stryCov_9fa48("32"), 'REGISTER_USER');
export const REGISTER_USER_SUCCESS = stryMutAct_9fa48("33") ? "" : (stryCov_9fa48("33"), 'REGISTER_USER_SUCCESS');
export const REGISTER_USER_ERROR = stryMutAct_9fa48("34") ? "" : (stryCov_9fa48("34"), 'REGISTER_USER_ERROR');
export const RESET_USER_PASSWORD = stryMutAct_9fa48("35") ? "" : (stryCov_9fa48("35"), 'RESET_USER_PASSWORD');
export const RESET_USER_PASSWORD_SUCCESS = stryMutAct_9fa48("36") ? "" : (stryCov_9fa48("36"), 'RESET_USER_PASSWORD_SUCCESS');
export const RESET_USER_PASSWORD_ERROR = stryMutAct_9fa48("37") ? "" : (stryCov_9fa48("37"), 'RESET_USER_PASSWORD_ERROR');
export const ACTIVATE_USER = stryMutAct_9fa48("38") ? "" : (stryCov_9fa48("38"), 'ACTIVATE_USER');
export const ACTIVATE_USER_SUCCESS = stryMutAct_9fa48("39") ? "" : (stryCov_9fa48("39"), 'ACTIVATE_USER_SUCCESS');
export const ACTIVATE_USER_ERROR = stryMutAct_9fa48("40") ? "" : (stryCov_9fa48("40"), 'ACTIVATE_USER_ERROR');
export const SET_LOADING_INDICATOR = stryMutAct_9fa48("41") ? "" : (stryCov_9fa48("41"), 'SET_LOADING_INDICATOR');
export const SET_AUTH_LOADING_INDICATOR = stryMutAct_9fa48("42") ? "" : (stryCov_9fa48("42"), 'SET_AUTH_LOADING_INDICATOR');
export const SET_SCHEDULE_LOADING_INDICATOR = stryMutAct_9fa48("43") ? "" : (stryCov_9fa48("43"), 'SET_SCHEDULE_LOADING_INDICATOR');
export const SET_MAIN_SCHEDULE_LOADING_INDICATOR = stryMutAct_9fa48("44") ? "" : (stryCov_9fa48("44"), 'SET_MAIN_SCHEDULE_LOADING_INDICATOR');
export const SET_SEMESTER_LOADING_INDICATOR = stryMutAct_9fa48("45") ? "" : (stryCov_9fa48("45"), 'SET_SEMESTER_LOADING_INDICATOR');
export const SET_STUDENTS_LOADING_INDICATOR = stryMutAct_9fa48("46") ? "" : (stryCov_9fa48("46"), 'SET_STUDENTS_LOADING_INDICATOR');
export const SET_ROOMS_LOADING_INDICATOR = stryMutAct_9fa48("47") ? "" : (stryCov_9fa48("47"), 'SET_ROOMS_LOADING_INDICATOR');
export const GET_SCHEDULE_ITEMS_START = stryMutAct_9fa48("48") ? "" : (stryCov_9fa48("48"), 'GET_SCHEDULE_ITEMS_START');
export const GET_SCHEDULE_ITEMS_SUCCESS = stryMutAct_9fa48("49") ? "" : (stryCov_9fa48("49"), 'GET_SCHEDULE_ITEMS_SUCCESS');
export const SET_PLACE = stryMutAct_9fa48("50") ? "" : (stryCov_9fa48("50"), 'SET_PLACE');
export const SELECT_GROUP_SCHEDULE_START = stryMutAct_9fa48("51") ? "" : (stryCov_9fa48("51"), 'SELECT_GROUP_SCHEDULE_START');
export const SELECT_TEACHER_SCHEDULE_START = stryMutAct_9fa48("52") ? "" : (stryCov_9fa48("52"), 'SELECT_TEACHER_SCHEDULE_START');
export const SELECT_FULL_SCHEDULE_START = stryMutAct_9fa48("53") ? "" : (stryCov_9fa48("53"), 'SELECT_FULL_SCHEDULE_START');
export const DRAG_AND_DROP_ROOM_START = stryMutAct_9fa48("54") ? "" : (stryCov_9fa48("54"), 'DRAG_AND_DROP_ROOM_START');
export const UPDATE_ROOM_ORDER_SUCCESS = stryMutAct_9fa48("55") ? "" : (stryCov_9fa48("55"), 'UPDATE_ROOM_ORDER_SUCCESS');
export const CHECK_AVAILABILITY_CHANGE_ROOM_SCHEDULE_START = stryMutAct_9fa48("56") ? "" : (stryCov_9fa48("56"), 'CHECK_AVAILABILITY_CHANGE_ROOM_SCHEDULE_START');
export const CHECK_AVAILABILITY_CHANGE_ROOM_SCHEDULE_SUCCESS = stryMutAct_9fa48("57") ? "" : (stryCov_9fa48("57"), 'CHECK_AVAILABILITY_CHANGE_ROOM_SCHEDULE_SUCCESS');
export const GET_CURRENT_SEMESTER_START = stryMutAct_9fa48("58") ? "" : (stryCov_9fa48("58"), 'GET_CURRENT_SEMESTER_START');
export const GET_CURRENT_SEMESTER_SUCCESS = stryMutAct_9fa48("59") ? "" : (stryCov_9fa48("59"), 'GET_CURRENT_SEMESTER_SUCCESS');
export const GET_ALL_PUBLIC_TEACHERS_START = stryMutAct_9fa48("60") ? "" : (stryCov_9fa48("60"), 'GET_ALL_PUBLIC_TEACHERS_START');
export const GET_ALL_PUBLIC_SEMESTERS_START = stryMutAct_9fa48("61") ? "" : (stryCov_9fa48("61"), 'GET_ALL_PUBLIC_SEMESTERS_START');
export const GET_ALL_PUBLIC_SEMESTERS_SUCCESS = stryMutAct_9fa48("62") ? "" : (stryCov_9fa48("62"), 'GET_ALL_PUBLIC_SEMESTERS_SUCCESS');
export const GET_ALL_SCHEDULE_ITEMS_START = stryMutAct_9fa48("63") ? "" : (stryCov_9fa48("63"), 'GET_ALL_SCHEDULE_ITEMS_START');
export const GET_ALL_PUBLIC_GROUPS_START = stryMutAct_9fa48("64") ? "" : (stryCov_9fa48("64"), 'GET_ALL_PUBLIC_GROUPS_START');
export const SEND_TEACHER_SCHEDULE_START = stryMutAct_9fa48("65") ? "" : (stryCov_9fa48("65"), 'SEND_TEACHER_SCHEDULE_START');
export const GET_TEACHER_RANGE_SCHEDULE_START = stryMutAct_9fa48("66") ? "" : (stryCov_9fa48("66"), 'GET_TEACHER_RANGE_SCHEDULE_START');
export const GET_TEACHER_RANGE_SCHEDULE_SUCCESS = stryMutAct_9fa48("67") ? "" : (stryCov_9fa48("67"), 'GET_TEACHER_RANGE_SCHEDULE_SUCCESS');
export const GET_DEFAULT_SEMESTER_START = stryMutAct_9fa48("68") ? "" : (stryCov_9fa48("68"), 'GET_DEFAULT_SEMESTER_START');
export const GET_DEFAULT_SEMESTER_SUCCESS = stryMutAct_9fa48("69") ? "" : (stryCov_9fa48("69"), 'GET_DEFAULT_SEMESTER_SUCCESS');
export const ADD_ITEM_TO_SCHEDULE = stryMutAct_9fa48("70") ? "" : (stryCov_9fa48("70"), 'ADD_ITEM_TO_SCHEDULE');
export const ADD_ITEM_TO_SCHEDULE_START = stryMutAct_9fa48("71") ? "" : (stryCov_9fa48("71"), 'ADD_ITEM_TO_SCHEDULE_START');
export const EDIT_ITEM_TO_SCHEDULE_START = stryMutAct_9fa48("72") ? "" : (stryCov_9fa48("72"), 'EDIT_ITEM_TO_SCHEDULE_START');
export const DELETE_SCHEDULE_ITEM_START = stryMutAct_9fa48("73") ? "" : (stryCov_9fa48("73"), 'DELETE_SCHEDULE_ITEM_START');
export const DELETE_SCHEDULE_ITEM_SUCCESS = stryMutAct_9fa48("74") ? "" : (stryCov_9fa48("74"), 'DELETE_SCHEDULE_ITEM_SUCCESS');
export const CLEAR_SCHEDULE_START = stryMutAct_9fa48("75") ? "" : (stryCov_9fa48("75"), 'CLEAR_SCHEDULE_START');
export const CHECK_AVAILABILITY_SCHEDULE_START = stryMutAct_9fa48("76") ? "" : (stryCov_9fa48("76"), 'CHECK_AVAILABILITY_SCHEDULE_START');
export const GET_FULL_SCHEDULE_START = stryMutAct_9fa48("77") ? "" : (stryCov_9fa48("77"), 'GET_FULL_SCHEDULE_START');
export const GET_FULL_SCHEDULE_SUCCESS = stryMutAct_9fa48("78") ? "" : (stryCov_9fa48("78"), 'GET_FULL_SCHEDULE_SUCCESS');
export const GET_GROUP_SCHEDULE_START = stryMutAct_9fa48("79") ? "" : (stryCov_9fa48("79"), 'GET_GROUP_SCHEDULE_START');
export const GET_GROUP_SCHEDULE_SUCCESS = stryMutAct_9fa48("80") ? "" : (stryCov_9fa48("80"), 'GET_GROUP_SCHEDULE_SUCCESS');
export const GET_TEACHER_SCHEDULE_START = stryMutAct_9fa48("81") ? "" : (stryCov_9fa48("81"), 'GET_TEACHER_SCHEDULE_START');
export const GET_TEACHER_SCHEDULE_SUCCESS = stryMutAct_9fa48("82") ? "" : (stryCov_9fa48("82"), 'GET_TEACHER_SCHEDULE_SUCCESS');
export const GET_BUSY_ROOMS_START = stryMutAct_9fa48("83") ? "" : (stryCov_9fa48("83"), 'GET_BUSY_ROOMS_START');
export const GET_BUSY_ROOMS_SUCCESS = stryMutAct_9fa48("84") ? "" : (stryCov_9fa48("84"), 'GET_BUSY_ROOMS_SUCCESS');
export const SET_SCHEDULE_TYPE = stryMutAct_9fa48("85") ? "" : (stryCov_9fa48("85"), 'SET_SCHEDULE_TYPE');
export const DELETE_ITEM_FROM_SCHEDULE = stryMutAct_9fa48("86") ? "" : (stryCov_9fa48("86"), 'DELETE_ITEM_FROM_SCHEDULE');
export const SET_ITEM_GROUP_ID = stryMutAct_9fa48("87") ? "" : (stryCov_9fa48("87"), 'SET_ITEM_GROUP_ID');
export const GET_ALL_PUBLIC_TEACHERS_BY_DEPARTMENT_START = stryMutAct_9fa48("88") ? "" : (stryCov_9fa48("88"), 'GET_ALL_PUBLIC_TEACHERS_BY_DEPARTMENT_START');
export const ADD_TEACHER_SUCCESS = stryMutAct_9fa48("89") ? "" : (stryCov_9fa48("89"), 'ADD_TEACHER_SUCCESS');
export const ADD_TEACHER_START = stryMutAct_9fa48("90") ? "" : (stryCov_9fa48("90"), 'ADD_TEACHER_START');
export const HANDLE_TEACHER_START = stryMutAct_9fa48("91") ? "" : (stryCov_9fa48("91"), 'HANDLE_TEACHER_START');
export const SELECT_TEACHER = stryMutAct_9fa48("92") ? "" : (stryCov_9fa48("92"), 'SELECT_TEACHER');
export const SET_TEACHER = stryMutAct_9fa48("93") ? "" : (stryCov_9fa48("93"), 'SET_TEACHER');
export const UPDATE_TEACHER_SUCCESS = stryMutAct_9fa48("94") ? "" : (stryCov_9fa48("94"), 'UPDATE_TEACHER_SUCCESS');
export const UPDATE_TEACHER_START = stryMutAct_9fa48("95") ? "" : (stryCov_9fa48("95"), 'UPDATE_TEACHER_START');
export const DELETE_TEACHER_SUCCESS = stryMutAct_9fa48("96") ? "" : (stryCov_9fa48("96"), 'DELETE_TEACHER_SUCCESS');
export const DELETE_TEACHER_START = stryMutAct_9fa48("97") ? "" : (stryCov_9fa48("97"), 'DELETE_TEACHER_START');
export const SHOW_ALL_TEACHERS_SUCCESS = stryMutAct_9fa48("98") ? "" : (stryCov_9fa48("98"), 'SHOW_ALL_TEACHERS_SUCCESS');
export const SHOW_ALL_TEACHERS_START = stryMutAct_9fa48("99") ? "" : (stryCov_9fa48("99"), 'SHOW_ALL_TEACHERS_START');
export const GET_TEACHERS_WITHOUT_ACCOUNT_START = stryMutAct_9fa48("100") ? "" : (stryCov_9fa48("100"), 'GET_TEACHERS_WITHOUT_ACCOUNT_START');
export const GET_TEACHERS_WITHOUT_ACCOUNT_SUCCESS = stryMutAct_9fa48("101") ? "" : (stryCov_9fa48("101"), 'GET_TEACHERS_WITHOUT_ACCOUNT_SUCCESS');
export const GET_TEACHERS_BY_DEPARTMENT = stryMutAct_9fa48("102") ? "" : (stryCov_9fa48("102"), 'GET_TEACHERS_BY_DEPARTMENT');
export const CLASS_FORM_HANDLER = stryMutAct_9fa48("103") ? "" : (stryCov_9fa48("103"), 'CLASS_FORM_HANDLER');
export const ADD_CLASS_SCHEDULE_START = stryMutAct_9fa48("104") ? "" : (stryCov_9fa48("104"), 'ADD_CLASS_SCHEDULE_START');
export const GET_CLASS_SCHEDULE_LIST_START = stryMutAct_9fa48("105") ? "" : (stryCov_9fa48("105"), 'GET_CLASS_SCHEDULE_LIST_START');
export const GET_CLASS_SCHEDULE_BY_ID_START = stryMutAct_9fa48("106") ? "" : (stryCov_9fa48("106"), 'GET_CLASS_SCHEDULE_BY_ID_START');
export const DELETE_CLASS_SCHEDULE_START = stryMutAct_9fa48("107") ? "" : (stryCov_9fa48("107"), 'DELETE_CLASS_SCHEDULE_START');
export const UPDATE_CLASS_SCHEDULE_START = stryMutAct_9fa48("108") ? "" : (stryCov_9fa48("108"), 'UPDATE_CLASS_SCHEDULE_START');
export const CLEAR_CLASS_SCHEDULE_START = stryMutAct_9fa48("109") ? "" : (stryCov_9fa48("109"), 'CLEAR_CLASS_SCHEDULE_START');
export const GET_PUBLIC_CLASS_SCHEDULE_LIST_START = stryMutAct_9fa48("110") ? "" : (stryCov_9fa48("110"), 'GET_PUBLIC_CLASS_SCHEDULE_LIST_START');
export const ADD_CLASS_SCHEDULE_SUCCESS = stryMutAct_9fa48("111") ? "" : (stryCov_9fa48("111"), 'ADD_CLASS_SCHEDULE_SUCCESS');
export const GET_CLASS_SCHEDULE_LIST_SUCCESS = stryMutAct_9fa48("112") ? "" : (stryCov_9fa48("112"), 'GET_CLASS_SCHEDULE_LIST_SUCCESS');
export const GET_CLASS_SCHEDULE_BY_ID_SUCCESS = stryMutAct_9fa48("113") ? "" : (stryCov_9fa48("113"), 'GET_CLASS_SCHEDULE_BY_ID__SUCCESS');
export const DELETE_CLASS_SCHEDULE_SUCCESS = stryMutAct_9fa48("114") ? "" : (stryCov_9fa48("114"), 'DELETE_CLASS_SCHEDULE_SUCCESS');
export const UPDATE_CLASS_SCHEDULE_SUCCESS = stryMutAct_9fa48("115") ? "" : (stryCov_9fa48("115"), 'UPDATE_CLASS_SCHEDULE_SUCCESS');
export const CLEAR_CLASS_SCHEDULE_SUCCESS = stryMutAct_9fa48("116") ? "" : (stryCov_9fa48("116"), 'CLEAR_CLASS_SCHEDULE_SUCCESS');
export const GET_PUBLIC_CLASS_SCHEDULE_LIST_SUCCESS = stryMutAct_9fa48("117") ? "" : (stryCov_9fa48("117"), 'GET_PUBLIC_CLASS_SCHEDULE_LIST_SUCCESS');
export const ADD_ROOM = stryMutAct_9fa48("118") ? "" : (stryCov_9fa48("118"), 'ADD_ROOM');
export const ADD_ROOM_START = stryMutAct_9fa48("119") ? "" : (stryCov_9fa48("119"), 'ADD_ROOM_START');
export const DELETE_ROOM = stryMutAct_9fa48("120") ? "" : (stryCov_9fa48("120"), 'DELETE_ROOM');
export const DELETE_ROOM_START = stryMutAct_9fa48("121") ? "" : (stryCov_9fa48("121"), 'DELETE_ROOM_START');
export const SHOW_LIST_OF_ROOMS_SUCCESS = stryMutAct_9fa48("122") ? "" : (stryCov_9fa48("122"), 'SHOW_LIST_OF_ROOMS_SUCCESS');
export const GET_LIST_OF_ROOMS_START = stryMutAct_9fa48("123") ? "" : (stryCov_9fa48("123"), 'GET_LIST_OF_ROOMS_START');
export const GET_LIST_OF_DISABLED_ROOMS_START = stryMutAct_9fa48("124") ? "" : (stryCov_9fa48("124"), 'GET_LIST_OF_DISABLED_ROOMS_START');
export const SET_SELECT_ROOM = stryMutAct_9fa48("125") ? "" : (stryCov_9fa48("125"), 'SET_SELECT_ROOM');
export const UPDATE_ROOM = stryMutAct_9fa48("126") ? "" : (stryCov_9fa48("126"), 'UPDATE_ROOM');
export const UPDATE_ROOM_START = stryMutAct_9fa48("127") ? "" : (stryCov_9fa48("127"), 'UPDATE_ROOM_START');
export const CLEAR_ROOM = stryMutAct_9fa48("128") ? "" : (stryCov_9fa48("128"), 'CLEAR_ROOM');
export const GET_ALL_ROOM_TYPES = stryMutAct_9fa48("129") ? "" : (stryCov_9fa48("129"), 'GET_ALL_ROOM_TYPES');
export const GET_ALL_ROOM_TYPES_START = stryMutAct_9fa48("130") ? "" : (stryCov_9fa48("130"), 'GET_ALL_ROOM_TYPES_START');
export const ADD_ROOM_TYPE = stryMutAct_9fa48("131") ? "" : (stryCov_9fa48("131"), 'ADD_ROOM_TYPE');
export const DELETE_ROOM_TYPE = stryMutAct_9fa48("132") ? "" : (stryCov_9fa48("132"), 'DELETE_ROOM_TYPE');
export const DELETE_ROOM_TYPE_START = stryMutAct_9fa48("133") ? "" : (stryCov_9fa48("133"), 'DELETE_ROOM_TYPE_START');
export const SELECT_ROOM_TYPE = stryMutAct_9fa48("134") ? "" : (stryCov_9fa48("134"), 'SELECT_ROOM_TYPE');
export const UPDATE_ROOM_TYPE = stryMutAct_9fa48("135") ? "" : (stryCov_9fa48("135"), 'UPDATE_ROOM_TYPE');
export const CLEAR_ONE_NEW_TYPE = stryMutAct_9fa48("136") ? "" : (stryCov_9fa48("136"), 'CLEAR_ONE_NEW_TYPE');
export const GET_FREE_ROOMS_START = stryMutAct_9fa48("137") ? "" : (stryCov_9fa48("137"), 'GET_FREE_ROOMS_START');
export const GET_FREE_ROOMS_SUCCESS = stryMutAct_9fa48("138") ? "" : (stryCov_9fa48("138"), 'GET_FREE_ROOMS_SUCCESS');
export const CLEAR_FREE_ROOM = stryMutAct_9fa48("139") ? "" : (stryCov_9fa48("139"), 'CLEAR_FREE_ROOM');
export const HANDLE_ROOM_FORM_SUBMIT_START = stryMutAct_9fa48("140") ? "" : (stryCov_9fa48("140"), 'HANDLE_ROOM_FORM_SUBMIT_START');
export const HANDLE_ROOM_TYPE_FORM_SUBMIT_START = stryMutAct_9fa48("141") ? "" : (stryCov_9fa48("141"), 'HANDLE_ROOM_TYPE_FORM_SUBMIT_START');
export const TOGGLE_ROOM_VISIBILITY_START = stryMutAct_9fa48("142") ? "" : (stryCov_9fa48("142"), 'TOGGLE_ROOM_VISIBILITY_START');
export const CLEAR_FREE_ROOMS = stryMutAct_9fa48("143") ? "" : (stryCov_9fa48("143"), 'CLEAR_FREE_ROOMS');
export const ADD_SUBJECT = stryMutAct_9fa48("144") ? "" : (stryCov_9fa48("144"), 'ADD_SUBJECT');
export const DELETE_SUBJECT = stryMutAct_9fa48("145") ? "" : (stryCov_9fa48("145"), 'DELETE_SUBJECT');
export const SHOW_ALL_SUBJECTS = stryMutAct_9fa48("146") ? "" : (stryCov_9fa48("146"), 'SHOW_ALL_SUBJECT');
export const SELECT_SUBJECT = stryMutAct_9fa48("147") ? "" : (stryCov_9fa48("147"), 'SELECT_SUBJECT');
export const UPDATE_SUBJECT = stryMutAct_9fa48("148") ? "" : (stryCov_9fa48("148"), 'UPDATE_SUBJECT');
export const CLEAR_SUBJECT = stryMutAct_9fa48("149") ? "" : (stryCov_9fa48("149"), 'CLEAR_SUBJECT');
export const ADD_DEPARTMENT = stryMutAct_9fa48("150") ? "" : (stryCov_9fa48("150"), 'ADD_DEPARTMENT');
export const GET_ALL_DEPARTMENTS = stryMutAct_9fa48("151") ? "" : (stryCov_9fa48("151"), 'GET_ALL_DEPARTMENTS');
export const CLEAR_DEPARTMENT_FORM = stryMutAct_9fa48("152") ? "" : (stryCov_9fa48("152"), 'CLEAR_DEPARTMENT_FORM');
export const DELETE_DEPARTMENT = stryMutAct_9fa48("153") ? "" : (stryCov_9fa48("153"), 'DELETE_DEPARTMENT');
export const GET_DISABLED_DEPARTMENTS = stryMutAct_9fa48("154") ? "" : (stryCov_9fa48("154"), 'GET_DISABLED_DEPARTMENTS');
export const SET_DISABLED_DEPARTMENT = stryMutAct_9fa48("155") ? "" : (stryCov_9fa48("155"), 'SET_DISABLED_DEPARTMENT');
export const SET_ENABLED_DEPARTMENT = stryMutAct_9fa48("156") ? "" : (stryCov_9fa48("156"), 'SET_ENABLED_DEPARTMENT');
export const GET_DEPARTMENT_BY_ID = stryMutAct_9fa48("157") ? "" : (stryCov_9fa48("157"), 'GET_DEPARTMENT_BY_ID');
export const UPDATE_DEPARTMENT = stryMutAct_9fa48("158") ? "" : (stryCov_9fa48("158"), 'UPDATE_DEPARTMENT');
export const SET_SCHEDULE_GROUP = stryMutAct_9fa48("159") ? "" : (stryCov_9fa48("159"), 'SET_SCHEDULE_GROUP');
export const ADD_SEMESTER_SUCCESS = stryMutAct_9fa48("160") ? "" : (stryCov_9fa48("160"), 'ADD_SEMESTER_SUCCESS');
export const ADD_SEMESTER_START = stryMutAct_9fa48("161") ? "" : (stryCov_9fa48("161"), 'ADD_SEMESTER_START');
export const DELETE_SEMESTER_SUCCESS = stryMutAct_9fa48("162") ? "" : (stryCov_9fa48("162"), 'DELETE_SEMESTER_SUCCESS');
export const DELETE_SEMESTER_START = stryMutAct_9fa48("163") ? "" : (stryCov_9fa48("163"), 'DELETE_SEMESTER_START');
export const SHOW_ALL_SEMESTERS_SUCCESS = stryMutAct_9fa48("164") ? "" : (stryCov_9fa48("164"), 'SHOW_ALL_SEMESTER');
export const GET_ALL_SEMESTERS_START = stryMutAct_9fa48("165") ? "" : (stryCov_9fa48("165"), 'GET_ALL_SEMESTER_START');
export const SELECT_SEMESTER_SUCCESS = stryMutAct_9fa48("166") ? "" : (stryCov_9fa48("166"), 'SELECT_SEMESTER_SUCCESS');
export const UPDATE_SEMESTER_SUCCESS = stryMutAct_9fa48("167") ? "" : (stryCov_9fa48("167"), 'UPDATE_SEMESTER_SUCCESS');
export const UPDATE_SEMESTER_START = stryMutAct_9fa48("168") ? "" : (stryCov_9fa48("168"), 'UPDATE_SEMESTER_START');
export const UPDATE_SEMESTER_BY_ID_START_SUCCESS = stryMutAct_9fa48("169") ? "" : (stryCov_9fa48("169"), 'UPDATE_SEMESTER_BY_ID_START_SUCCESS');
export const HANDLE_SEMESTER_FORM_SUBMIT_START = stryMutAct_9fa48("170") ? "" : (stryCov_9fa48("170"), 'HANDLE_SEMESTER_FORM_SUBMIT_START');
export const SET_SEMESTER_COPY_START = stryMutAct_9fa48("171") ? "" : (stryCov_9fa48("171"), 'SEMESTER_COPY_START');
export const COPY_LESSONS_FROM_SEMESTER_START = stryMutAct_9fa48("172") ? "" : (stryCov_9fa48("172"), 'COPY_LESSONS_FROM_SEMESTER_START');
export const CLEAR_SEMESTER_SUCCESS = stryMutAct_9fa48("173") ? "" : (stryCov_9fa48("173"), 'CLEAR_SEMESTER_SUCCESS');
export const SET_ERROR = stryMutAct_9fa48("174") ? "" : (stryCov_9fa48("174"), 'SET_ERROR');
export const SET_ARCHIVED_SEMESTERS_SUCCESS = stryMutAct_9fa48("175") ? "" : (stryCov_9fa48("175"), 'SET_ARCHIVED_SEMESTERS_SUCCESS');
export const SET_ARCHIVED_SEMESTERS_START = stryMutAct_9fa48("176") ? "" : (stryCov_9fa48("176"), 'SET_ARCHIVED_SEMESTERS_START');
export const GET_ARCHIVE_SEMESTER_BY_ID_START = stryMutAct_9fa48("177") ? "" : (stryCov_9fa48("177"), 'GET_ARCHIVE_SEMESTER_BY_ID_START');
export const CREATE_ARCHIVE_SEMESTER_START = stryMutAct_9fa48("178") ? "" : (stryCov_9fa48("178"), 'CREATE_ARCHIVE_SEMESTER_START');
export const SET_GROUPS_TO_SEMESTER_START = stryMutAct_9fa48("179") ? "" : (stryCov_9fa48("179"), 'SET_GROUPS_TO_SEMESTER_START');
export const TOGGLE_SEMESTER_VISIBILITY_START = stryMutAct_9fa48("180") ? "" : (stryCov_9fa48("180"), 'TOGGLE_SEMESTER_VISIBILITY_START');
export const SET_DISABLED_ROOMS = stryMutAct_9fa48("181") ? "" : (stryCov_9fa48("181"), 'SET_DISABLED_ROOMS');
export const SET_DISABLED_TEACHERS_SUCCESS = stryMutAct_9fa48("182") ? "" : (stryCov_9fa48("182"), 'SET_DISABLED_TEACHERS_SUCCESS');
export const SET_DISABLED_TEACHERS_START = stryMutAct_9fa48("183") ? "" : (stryCov_9fa48("183"), 'SET_DISABLED_TEACHERS_START');
export const SET_DISABLED_GROUPS = stryMutAct_9fa48("184") ? "" : (stryCov_9fa48("184"), 'SET_DISABLED_GROUPS');
export const SET_DISABLED_SEMESTERS_SUCCESS = stryMutAct_9fa48("185") ? "" : (stryCov_9fa48("185"), 'SET_DISABLED_SEMESTERS_SUCCESS');
export const GET_DISABLED_SEMESTERS_START = stryMutAct_9fa48("186") ? "" : (stryCov_9fa48("186"), 'GET_DISABLED_SEMESTERS_START');
export const SET_DISABLED_SUBJECTS = stryMutAct_9fa48("187") ? "" : (stryCov_9fa48("187"), 'SET_DISABLED_SUBJECTS');
export const SET_SCHEDULE_TEACHER = stryMutAct_9fa48("188") ? "" : (stryCov_9fa48("188"), 'SET_SCHEDULE_TEACHER');
export const SET_SCHEDULE_SEMESTER = stryMutAct_9fa48("189") ? "" : (stryCov_9fa48("189"), 'SET_SCHEDULE_SEMESTER');
export const SET_TEACHER_VIEW_TYPE = stryMutAct_9fa48("190") ? "" : (stryCov_9fa48("190"), 'SET_TEACHER_VIEW_TYPE');
export const MOVE_SEMESTER_TO_ARCHIVE_SUCCESS = stryMutAct_9fa48("191") ? "" : (stryCov_9fa48("191"), 'MOVE_SEMESTER_TO_ARCHIVE_SUCCESS');
export const SET_IS_OPEN_CONFIRM_DIALOG = stryMutAct_9fa48("192") ? "" : (stryCov_9fa48("192"), 'SET_IS_OPEN_CONFIRM_DIALOG');
export const GET_GROUP_BY_ID_SUCCESS = stryMutAct_9fa48("193") ? "" : (stryCov_9fa48("193"), 'GET_GROUP_BY_ID_SUCCESS');
export const SHOW_ALL_GROUPS_SUCCESS = stryMutAct_9fa48("194") ? "" : (stryCov_9fa48("194"), 'SHOW_ALL_GROUPS_SUCCESS');
export const DELETE_GROUP_SUCCESS = stryMutAct_9fa48("195") ? "" : (stryCov_9fa48("195"), 'DELETE_GROUP_SUCCESS');
export const SELECT_GROUP_SUCCESS = stryMutAct_9fa48("196") ? "" : (stryCov_9fa48("196"), 'SELECT_GROUP_SUCCESS');
export const UPDATE_GROUP_SUCCESS = stryMutAct_9fa48("197") ? "" : (stryCov_9fa48("197"), 'UPDATE_GROUP_SUCCESS');
export const CREATE_GROUP_SUCCESS = stryMutAct_9fa48("198") ? "" : (stryCov_9fa48("198"), 'CREATE_GROUP_SUCCESS');
export const CLEAR_GROUP_SUCCESS = stryMutAct_9fa48("199") ? "" : (stryCov_9fa48("199"), 'CLEAR_GROUP_SUCCESS');
export const TOGGLE_DISABLED_STATUS_GROUP = stryMutAct_9fa48("200") ? "" : (stryCov_9fa48("200"), 'TOGGLE_DISABLED_STATUS_GROUP');
export const DRAG_AND_DROP_GROUP_START = stryMutAct_9fa48("201") ? "" : (stryCov_9fa48("201"), 'DRAG_AND_DROP_GROUP_START');
export const GET_DISABLED_GROUPS_START = stryMutAct_9fa48("202") ? "" : (stryCov_9fa48("202"), 'GET_DISABLED_GROUPS_START');
export const GET_ENABLED_GROUPS_START = stryMutAct_9fa48("203") ? "" : (stryCov_9fa48("203"), 'GET_ENABLED_GROUPS_START');
export const GET_GROUP_BY_ID_START = stryMutAct_9fa48("204") ? "" : (stryCov_9fa48("204"), 'GET_GROUP_BY_ID_START');
export const DELETE_GROUP_START = stryMutAct_9fa48("205") ? "" : (stryCov_9fa48("205"), 'DELETE_GROUP_START');
export const SUBMIT_GROUP_START = stryMutAct_9fa48("206") ? "" : (stryCov_9fa48("206"), 'SUBMIT_GROUP_START');
export const CLEAR_GROUP_START = stryMutAct_9fa48("207") ? "" : (stryCov_9fa48("207"), 'CLEAR_GROUP_START');
export const SHOW_ALL_STUDENTS_BY_GROUP_ID = stryMutAct_9fa48("208") ? "" : (stryCov_9fa48("208"), 'SHOW_ALL_STUDENTS_BY_GROUP_ID');
export const SHOW_ALL_STUDENTS = stryMutAct_9fa48("209") ? "" : (stryCov_9fa48("209"), 'SHOW_ALL_STUDENTS');
export const DELETE_STUDENT = stryMutAct_9fa48("210") ? "" : (stryCov_9fa48("210"), 'DELETE_STUDENT');
export const UPDATE_STUDENT = stryMutAct_9fa48("211") ? "" : (stryCov_9fa48("211"), 'UPDATE_STUDENT');
export const CREATE_STUDENT = stryMutAct_9fa48("212") ? "" : (stryCov_9fa48("212"), 'CREATE_STUDENT');
export const SET_STUDENT = stryMutAct_9fa48("213") ? "" : (stryCov_9fa48("213"), 'SET_STUDENT');
export const MOVE_STUDENTS_TO_GROUP_START = stryMutAct_9fa48("214") ? "" : (stryCov_9fa48("214"), 'MOVE_STUDENTS_TO_GROUP_START');
export const UPLOAD_FILE_STUDENT_START = stryMutAct_9fa48("215") ? "" : (stryCov_9fa48("215"), 'UPLOAD_FILE_STUDENT_START');
export const CREATE_STUDENT_START = stryMutAct_9fa48("216") ? "" : (stryCov_9fa48("216"), 'CREATE_STUDENT_START');
export const UPDATE_STUDENT_START = stryMutAct_9fa48("217") ? "" : (stryCov_9fa48("217"), 'UPDATE_STUDENT_START');
export const DELETE_STUDENT_START = stryMutAct_9fa48("218") ? "" : (stryCov_9fa48("218"), 'DELETE_STUDENT_START');
export const SUBMIT_STUDENT_FORM = stryMutAct_9fa48("219") ? "" : (stryCov_9fa48("219"), 'SUBMIT_STUDENT_FORM');
export const DELETE_SELECTED_STUDENTS = stryMutAct_9fa48("220") ? "" : (stryCov_9fa48("220"), 'DELETE_SELECTED_STUDENTS');
export const GET_ALL_STUDENTS = stryMutAct_9fa48("221") ? "" : (stryCov_9fa48("221"), 'GET_ALL_STUDENTS');
export const CHECK_ALL_STUDENTS = stryMutAct_9fa48("222") ? "" : (stryCov_9fa48("222"), 'CHECK_ALL_STUDENTS');
export const GET_LESSONS_BY_TEACHER_START = stryMutAct_9fa48("223") ? "" : (stryCov_9fa48("223"), 'GET_LESSONS_BY_TEACHER_START');
export const GET_LESSONS_BY_TEACHER_SUCCESS = stryMutAct_9fa48("224") ? "" : (stryCov_9fa48("224"), 'GET_LESSONS_BY_TEACHER_SUCCESS');
export const UPDATE_LESSON_LINK_START = stryMutAct_9fa48("225") ? "" : (stryCov_9fa48("225"), 'UPDATE_LESSON_LINK_START');
export const UPDATE_LESSON_LINK_SUCCESS = stryMutAct_9fa48("226") ? "" : (stryCov_9fa48("226"), 'UPDATE_LESSON_LINK_SUCCESS');
export const CLEAR_TEACHER_LESSONS = stryMutAct_9fa48("227") ? "" : (stryCov_9fa48("227"), 'CLEAR_TEACHER_LESSONS');
export const SET_TEACHER_LESSONS_LOADING = stryMutAct_9fa48("228") ? "" : (stryCov_9fa48("228"), 'SET_TEACHER_LESSONS_LOADING');
export const UPDATE_LESSONS_LINK_START = stryMutAct_9fa48("229") ? "" : (stryCov_9fa48("229"), 'UPDATE_LESSONS_LINK_START');
export const UPDATE_LESSONS_LINK_SUCCESS = stryMutAct_9fa48("230") ? "" : (stryCov_9fa48("230"), 'UPDATE_LESSONS_LINK_SUCCESS');
export const SCHEDULE_NOT_PUBLISHED = stryMutAct_9fa48("231") ? "" : (stryCov_9fa48("231"), 'SCHEDULE_NOT_PUBLISHED');
export const SET_SCHEDULE_OPERATION_LOADING = stryMutAct_9fa48("232") ? "" : (stryCov_9fa48("232"), 'SET_SCHEDULE_OPERATION_LOADING');
export const SELECT_DEPARTMENT_SCHEDULE_START = stryMutAct_9fa48("233") ? "" : (stryCov_9fa48("233"), 'SELECT_DEPARTMENT_SCHEDULE_START');
export const SET_SCHEDULE_DEPARTMENT = stryMutAct_9fa48("234") ? "" : (stryCov_9fa48("234"), 'SET_SCHEDULE_DEPARTMENT');